apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-hello-world-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world-container
        image: bgcodehub/my-hello-world-nginx
        env:
        - name: SQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: sql-credentials
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-credentials
              key: password
